### ISSUE TITLE
该主题还在维护吗？

### ISSUE THREAD

**Issue by seguzhizi** [fooying/hexo-theme-xoxo-plus#1]
clone了该主题之后，发现文档落后啦，功能不太清楚如何实现，导致难以使用，作者还在维护吗?

**Comment by fooying** [comment]
需要对hexo有一定了解，这个可以参考hexo官方文档 https://hexo.io/zh-cn/docs ，不过官方文档本身也急需更新。碰到问题可以直接提issue哈
另外安装之后除了在根目录执行npm install，还需要在模板目录下同样执行该命令来安装模板额外依赖的一些包
